### ISSUE TITLE
Don't work in Zoomed display mode

### ISSUE THREAD

**Issue by retyui** [hoaphantn7604/react-native-utils-scale#1]
I enabled **Zoomed** mode for Display

![image](https://user-images.githubusercontent.com/4661784/146393477-acbdfce0-b861-439b-939a-284a3c7d1ad1.png)

And seem plugin return invalid data (and all my text become to small):

```tsx
// standard mode
{
  "window": { // Dimensions.get('window')
    "scale": 3,
    "width": 390,
    "height": 844,
    "fontScale": 1
  },
  "screen": { // Dimensions.get('screen')
    "scale": 3,
    "width": 390,
    "height": 844,
    "fontScale": 1
  },
  "PixelRatio_get": 3,
  "PixelRatio_getFontScale": 1,
  "fontScale_16": 14.4,
  "scale_10": 10,
  "deviceInch": 6.1,
  "hasNotch": true,
  "isAndroid": false,
  "isIOS": true,
  "isSmallDevice": false,
  "isTablet": false,
  "width": 390,
  "height": 844
}

// zoomed mode
{
  "window": {
    "scale": 3,
    "width": 320,
    "height": 693,
    "fontScale": 1
  },
  "screen": {
    "scale": 3,
    "width": 320,
    "height": 693,
    "fontScale": 1
  },
  "PixelRatio_get": 3,
  "PixelRatio_getFontScale": 1,
  "fontScale_16": 3.2,          // fontScale(16)
  "scale_10": 3,                    // scale (10)
  "deviceInch": 0,                 // How it can be ????? 
  "hasNotch": true,
  "isAndroid": false,
  "isIOS": true,
  "isSmallDevice": true,
  "isTablet": false,
  "width": 320,
  "height": 693
}
```

**Comment by davydspotnana** [comment]
<img width="832" alt="Screenshot 2021-12-16 at 18 01 29" src="https://user-images.githubusercontent.com/95620376/146399828-dadfe9ee-ea36-4982-aa79-f3be88a59c82.png">

**Comment by hoaphantn7604** [comment]
Thanks you,
I'm working on it.

**Comment by rawalhussain** [comment]
any progress on this issue

**Comment by hoaphantn7604** [comment]
hi @rawalhussain ,
You can apply:
allowFontScaling={false}
So, you can implement it like this:
```js
<Text allowFontScaling={false}>Do not want font to scale</Text>
```

**Comment by rawalhussain** [comment]
> hi @rawalhussain , You can apply: allowFontScaling={false} So, you can implement it like this:
> 
> ```js
> <Text allowFontScaling={false}>Do not want font to scale</Text>
> ```

This thing only work for font scaling what about apple zoom feature and android display scaling

**Comment by rawalhussain** [comment]
Device inches getting 0 if device is zoomed
